baseURL = "http://localhost:1313/PTEROSOR/"
#baseURL = "https://lcpq.github.io/PTEROSOR/"
canonifyurls  = true
languageCode = "en-us"
title = "ERC PTEROSOR"
DefaultContentLanguage = "en"
theme = "beautifulhugo"
[Params]
  hometitle = "ERC PTEROSOR"
  logo="img/PTEROSOR.png"
#  subtitle = ""
[[Params.bigimg]]
  src = "img/banner.png"
  desc = "A mountaineering strategy to excited states"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[Author]
  name = "P.-F. Loos"
  github = "pfloos"
  twitter = "pfloos"

[[menu.main]]
    name = "Home"
    url = ""
    weight = 1

[[menu.main]]
    name = "People"
    url = "people"
    weight = 2

[[menu.main]]
    name = "Software"
    url = "software"
    weight = 3

[[menu.main]]
    name = "Publications"
    url = "publications"
    weight = 4
